### ISSUE TITLE
Is it possible to use with Unity3D engine somehow?

### ISSUE THREAD

**Issue by ognjenmarcheta** [aarondandy/WeCantSpell.Hunspell#15]
Hi there, is it possible to use this port with unity3d game engine? I tried to implement it, but i failed. I guess problem is mono 2.0/3.5 and unity android platform.

**Comment by ognjenmarcheta** [comment]
Unity 2017 have .NET 4.5 so it's possible to make it with that version. Today i tested in beta and it was successful.

**Comment by aarondandy** [comment]
Thanks for letting me know, I was curious if that would work. A new release just went out today too which should perform better too.

**Comment by aarondandy** [comment]
@ognjenmarcheta , do you still have a use case for net35? If so would you mind mentioning something over in #34 ?
