### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by aarondandy** [aarondandy/WeCantSpell.Hunspell#3]
Because NetCore is not really a good library target anymore and because NetStandard may itself be a moving target (who knows?) I am going to rename this repository. The whole reason I started work on this port was to support another spelling related project I am working on. Because of this I think I will just turn that name (WeCantSpell) into an umbrella project containing both this Hunspell port as well as the tool that would consume it. Naming is hard, and ... whatever I'm tired of trying to pick a good one :) Nothing with respect to functionality will change but people referencing the pre-release packages will have to swap out some namespaces and a package.

**Comment by aarondandy** [comment]
I also want to notify @MonsterMMORPG and @rianjs about this upcoming project rename as they have commented on issues here already. The current name is kind of pewpy in my opinion and I want to get a namespace with a better shelf life before the first released package goes out. I should have everything sorted by Monday, maybe even some performance tweaks!

**Comment by aarondandy** [comment]
ping @devatwork too as a stargazer

**Comment by rianjs** [comment]
Just call it hunspell.net. That's what I did when I took over dday.ical.

Are you doing the C++ to C# manually or are you using a tool?

**Comment by aarondandy** [comment]
Yeah, I'm still debating calling it that or WeCantSpell.Hunspell or ... something else. I kind of like WeCantSpell.Hunspell personally and I think people are more likely to search nuget for spell instead of hunspell. `¯\_(ツ)_/¯`

I convert this by hand and use NCrunch with nearly 2000 test cases to make sure I did it right. I even found a couple bugs in the original code doing it this way. This also allows me to make sure I maximize my use of the framework and create an API that I hope is idiomatic.
