### ISSUE TITLE
Future target frameworks

### ISSUE THREAD

**Issue by aarondandy** [aarondandy/WeCantSpell.Hunspell#60]
Because the large gap between .NET 4.5 and .NET 6, I'm not sure yet if I want to continue supporting .NET versions that are out of support or that may soon be out of support. I'm doing some quick analysis of what versions should be supported by exploring github and nuget to see what is out there. Based on that, and my tolerance for adding in shims, I think I will be able to determine a new list of target frameworks for a future 4.x release containing possibly breaking changes. If anybody out there has any feedback, and is actually paying attention to this project, please let me know what framework versions you are targeting still.

**Comment by aarondandy** [comment]
Sure, working on a spellchecking library on a Friday night while getting drunk on carbonated water is totally fun, but is spell checking fun enough to put in a game? Apparently it is! I don't know much about Unity but it sounds like both the net4.x and netstandard options support a netstandard2.0 target, so I think that will be a required target in 4.x . Also, it's probably the most "portable" option right now for most software out there.

**Comment by aarondandy** [comment]
Looking over Microsoft's support schedule as well as looking at some quickly compiled data based on nuget usages, here is what I'm thinking for target frameworks:

For .NET "Core":
net6.0, net5.0, and netcoreapp3.1 should all be supported for at least a few months. net6 will be the only one of the three to see support past 2022 though. I think that makes net6.0 an important explicit target and will probably be good enough to work with net7.0 applications.

For full framework:

It appears that nobody is really using net45 anymore and for the one person out there, I don't plan on removing the 3.x releases from nuget, so that should still work. I figure if somebody is worried about updates, they wouldn't still be on net45. That isn't so say I'm definitely dropping the net45 target, but I _may_ drop it if it becomes a massive pain for me. Already, the lowest target that VS2022 seems to support out of the box is net451 so, it might help with contributions to drop support for net45. I think this being a spell check library means that nobody will want to contribute anyway though, so maybe that doesn't matter 🤷‍♂️. Ultimately, most usages seem to be net47+ with a smaller group around net461. Considering that everything below net462 will lose support by 2023, maybe net462 is a good candidate for the minimum full framework version.

Net standard:

Netstandard2.0 is just too important, it has to be included. This should also bring unity compatibility with it, along with other full framework support cases too.

Microsoft support schedule: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by aarondandy** [comment]
My current thinking for future targets is going to be `net6.0;netstandard2.0;net462` for a 4.x release. If anybody has good reasons for keeping net45 around, I'll hear them, but I would love to drop it going forward.

**Comment by aarondandy** [comment]
@Tigrisor, @funex, and @Acciai0: do any of you have opinions on target frameworks?

**Comment by Acciai0** [comment]
I totally agree with what you've already said. I can only speak from the perspective of what I need and for sure `netstandard 2.0` is a must for me. Then, thinking about the future of the library itself, it's clear that the future of .NET lies on the new .NET 6.0 and its future iterations, with both .NET Core and Framework slowly fading into past. It means that for sure `net 6.0` must be supported. Plus, `netstandard 2.0` will be able to carry most of the updates onto `net framework` while it lasts.

**Comment by funex** [comment]
net6.0;netstandard2.0 for the win!
