### ISSUE TITLE
Some suggestions have incorrect spelling

### ISSUE THREAD

**Issue by alex-ford-cambium** [aarondandy/WeCantSpell.Hunspell#86]
I've found a few cases where a misspelled word is suggested. This issue does not occur in the native C++ version.

But if I take a word like **abjurers** and put a typo in so that it is now **abmurers**, one of the suggested words is **abjureers**, which is not an English word. Here are a few more examples:

| Word| Word Misspelled| Bad Suggestion|
| ----------- | ----------- | ----------- |
| epoxied| epooied|poiseed
|jewelries|ewelries|jewelrys
|squabbles|suabbles|squabblees

**Comment by aarondandy** [comment]
To better prepare for reproduction, can you also provide the dictionaries and versions of this library (assuming latest) and [hunspell](https://github.com/hunspell/hunspell) involved?

**Comment by alex-ford-cambium** [comment]
I was able to reproduce this issue in version 5.0. and 4.0 and tested it in version 1.7.2 of Hunspell, which did not have the issue. I've attached a zip file with our dictionary and affix file although I've tested others and still had the issue. Thanks for looking into this!

[dictionary_files.zip](https://github.com/aarondandy/WeCantSpell.Hunspell/files/15133967/dictionary_files.zip)

**Comment by aarondandy** [comment]
@alex-ford-cambium Thanks for this report. I was able to get the issue fixed I think. let me know if this new version resolves the issue for you: https://www.nuget.org/packages/WeCantSpell.Hunspell/5.0.1
