### ISSUE TITLE
Support for UWP 

### ISSUE THREAD

**Issue by nirdil** [aarondandy/WeCantSpell.Hunspell#87]
I'm trying to use this package in a UWP app, but it works only when building the project in Debug mode.
When building in Release mode the build fails with the following error:

> ILT0038: 'WeCantSpell.Hunspell.WordEntryDetail' is a value type with a default constructor. Value types with default constructors are not currently supported. Consider using an explicit initialization function instead.

I believe that to resolve this error the default empty CTOR in the WordEntryDetail class needs to be removed.

**Comment by aarondandy** [comment]
I'm torn on if this would be a breaking change or not. It doesn't _feel_ breaking to me as it would be compile time compatible even though not binary compatible. I don't think a change here would have any substantial impact to most users, outside of it being more compatible, so it's probably safe to make.

**Comment by nirdil** [comment]
Structs shouldn't have empty constructors as they're already generated with ones, so I this wouldn't be breaking in terms of API...
I believe you can just remove the empty ctor, and change the Default field to this-

    public static WordEntryDetail Default { get; } = new WordEntryDetail(FlagSet.Empty, MorphSet.Empty, WordEntryOptions.None);

**Comment by aarondandy** [comment]
@nirdil , see if this new release helps with your issue and re-open if not: https://www.nuget.org/packages/WeCantSpell.Hunspell/5.1.0
