### ISSUE TITLE
Russian-English Bilingual not working correctly

### ISSUE THREAD

**Issue by drkorobov** [aarondandy/WeCantSpell.Hunspell#89]
Tested. Some text "в радостных **предвкушениях**"
Dictionary (dic + aff)
1. Russian - "предвкушениях" - ок , not misspelled.
2. Russian-English Bilingual - "предвкушениях" - bad , misspelled. Suggest  "**предвкушения х**" , "**предвкушения-х**" , and some ..."

**Comment by aarondandy** [comment]
To make this actionable, can you specify exactly which dictionary files you are using? To make things easier, can you confirm if the behavior in this port deviates from https://github.com/hunspell/hunspell ?

**Comment by drkorobov** [comment]
https://github.com/titoBouzout/Dictionaries/tree/314dc880a6a71aa924719e98471fd49d0e20dbbe
[Russian.aff](https://github.com/titoBouzout/Dictionaries/blob/314dc880a6a71aa924719e98471fd49d0e20dbbe/Russian.aff)
[Russian.aff](https://github.com/titoBouzout/Dictionaries/blob/314dc880a6a71aa924719e98471fd49d0e20dbbe/Russian.aff)
[Russian-English Bilingual.aff](https://github.com/titoBouzout/Dictionaries/blob/314dc880a6a71aa924719e98471fd49d0e20dbbe/Russian-English%20Bilingual.aff)
[Russian-English Bilingual.dic](https://github.com/titoBouzout/Dictionaries/blob/314dc880a6a71aa924719e98471fd49d0e20dbbe/Russian-English%20Bilingual.dic)

**Comment by aarondandy** [comment]
I think the issue here is with the dictionary. Can you confirm the if the origin hunspell has the same issue?

For "Russian", the dictionary file has `предвкушение/61` with a suffix `SFX 61 ие иях .` that I guess applies.

For "Russian-English Bilingual" the dictionary file has `предвкушение/38,24,79,80,39,25,81` but none of the `SFX` entries seem to match, strip, and append the `иях` suffix you are looking for.

**Comment by drkorobov** [comment]
> I think the issue here is with the dictionary. Can you confirm the if the origin hunspell has the same issue?
> 
I think so too. I don't plan integrate origin hunspell in my project and can't confirm.
May be dictionary used the  wrong `ия х` `ия-х`  suffix or uses several double suffix `ия`  `х`

**Comment by aarondandy** [comment]
Please do re-open this if you find a fault in the library.
