### ISSUE TITLE
Seems to skip some English words

### ISSUE THREAD

**Issue by niksedk** [aarondandy/WeCantSpell.Hunspell#90]
When I load the en_US.dic/en_US.aff files, the method `wordList.Check("hours");` returns false. The same for e.g. `years`

I have loaded all encodings and there are no affix warnings.

Any ideas?

[en_us.zip](https://github.com/user-attachments/files/17175963/en_us.zip)

**Comment by niksedk** [comment]
The above dictionary works fine in the original hunspell + NHunspell (by Thomas Meierhofer) + HunspellSharp,  so I really think this is a serious bug in WeCantSpell.

Do you a English dictionary that you recommend?

**Comment by aarondandy** [comment]
I was able to reproduce this in NHunspell, but considering it's age I don't place a lot of weight on that. I was able to get a reproduction against the origin hunspell importantly, so it does appear to be a deviation in behavior.

Regarding dictionaries, the following works for "hours", the English (American) dictionary in this repository works for me: https://github.com/titoBouzout/Dictionaries/

**Comment by aarondandy** [comment]
The specific aspect of these files causing the issue are the comments at the end of some of the affix file commands. I need to add some code to strip those comments off before processing the line.

**Comment by aarondandy** [comment]
@niksedk , this release should fix your issues: https://www.nuget.org/packages/WeCantSpell.Hunspell/5.2.1 . If it doesn't, please do re-open or make a new issue if you find anything else. Thanks for the report.

**Comment by niksedk** [comment]
Nice :)
All works fine now. 
And unit tests too 👍
